# Ejercicios Numpy

In [1]:
import numpy as np

___

## Parte I

- Crea un vector con valores de 10 a 49 en pasos de 0.5.

In [34]:
a=np.linspace(10, 49, round((49-10)/0.5+1))
aa=np.arange(10,49,0.5)
aa

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5,
       32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. ,
       37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5,
       43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. ,
       48.5])

- Muestra su dimensión y su tipo.

In [16]:
a.ndim

1

In [17]:
a.shape

(79,)

In [35]:
a.dtype

dtype('float64')

- Crea un array con los números que tu elijas de dimensiones 2x3.

In [21]:
b=np.array([[1,2,3],[4,5,6]])

- Redimensiona el array anterior a 3x2

In [23]:
b.resize(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

### Indexing y slicing:

- Crea un array unidimensional de 10 elemento aleatorios.

In [27]:
data = np.random.randn(10)
data

array([ 1.07740707, -1.44674867, -0.2480118 , -0.22621016,  0.51138558,
       -1.73940521,  1.05569025, -0.43979184, -1.39621282, -0.99537522])

- Crea un array bidimensional de 10x10 elementos aletorios.

In [28]:
data2 = np.random.rand(10,10)
data2

array([[ 0.66634629,  1.80473951,  2.80473958,  1.12245552, -0.43350963,
        -0.94974549,  0.37031636,  0.58798605,  0.80570226, -0.23560556],
       [-1.21534867,  0.19359719,  1.39850212,  0.56164473, -0.30038468,
         1.06004657,  0.91401436, -0.05513326, -0.67649307,  0.53244863],
       [-0.80732397,  0.49647113, -0.54563059,  0.50233149,  0.30427137,
        -0.68838791,  1.55186731, -0.32105805, -0.05744229, -0.71363274],
       [-2.32234185, -0.85960345,  0.37994389, -1.37982129,  0.30234577,
        -2.59919353, -0.38442341, -1.36663332,  0.00675186,  2.56466719],
       [ 0.21277665,  0.99518966, -0.74352622, -2.15162972,  0.75144603,
         0.98081802,  1.37159482, -1.20220294, -0.01403546,  0.1848092 ],
       [-0.41184321,  0.61155426,  1.11110897,  0.24636814,  0.32803025,
        -1.57536057, -1.00558907, -0.89569151,  0.45026275, -0.18563922],
       [-0.96146347,  0.19087393, -1.03141385, -1.15668271, -0.21969709,
        -0.64476282, -0.12554426, -0.31256655

- Accede al primer elemento y al penúltimo número de cada array. 

In [36]:
print(data[0],data[-2])
print("\n")
print(data2[0,0],data2[-1,-2])


1.0774070669321432 -1.3962128163041418


0.6663462874115825 1.0607101263833862


- Array unidimensional: muestra todos los elementos en posiciones pares desde la posición 6.

In [32]:
data[6::2]

array([ 1.05569025, -1.39621282])

- Array bidimensional: muestra una submatriz con las dos primeras filas y las tres primeras columnas.

In [39]:
muerte=data2[:2, :3]
muerte

array([[ 0.66634629,  1.80473951,  2.80473958],
       [-1.21534867,  0.19359719,  1.39850212]])

- Divide el array bidimensional en dos: uno con las 2 primera fila y otro con las siguientes filas

- Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la diagonal principal valgan 5 y el resto valgan n.

- Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

---

## Parte II

-  Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [7]:
def funcion(n,m,b):
    import numpy as np
    matriz=np.arange(n*m).reshape(n,m)
    if b:
        return matriz.T
    else:
        return matriz

funcion(3,3,True)
    

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

- Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [27]:
def funcion2 (x):
    c=np.where(x>0, False, True)
    if True in c:
        return "SI que hay"
    else:
        return "No hay"

import numpy as np
c=np.array([[1,2,3],[-4,5,6]])
funcion2(c)

'SI que hay'

-  Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

---

## Parte III

- Crea un vector de 30 elementos aleatorios y calcula su media.

In [29]:
gl=np.random.rand(30)
gl.mean()

0.42771690020760295

- Crea una matriz de 4x8 aleatoria y substrae la media por columnas.

In [57]:
gp=np.random.rand(32).reshape(4,8)
df=np.mean(gp,axis=0, keepdims=True)
f=gp-df
print(f)





[[ 0.11711757  0.24978399  0.17894553  0.33190753 -0.39855834 -0.11358449
  -0.43155572 -0.47981331]
 [ 0.0134702  -0.27311629  0.16755732 -0.30994259  0.05485717  0.12426683
   0.27577155  0.41212394]
 [-0.20473622  0.21951439 -0.15945328 -0.09404239 -0.05926128  0.0017411
   0.09557969 -0.08722064]
 [ 0.07414845 -0.19618209 -0.18704957  0.07207746  0.40296244 -0.01242345
   0.06020448  0.15491   ]]


- Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto matricial de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

In [ ]:
def funcion (n,m):
    launo=np.random.normal()
    

- Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la unión de los elementos únicos de ambas.

- Cree una matriz aleatoria normal de 5x10 y normalícela en media y varianza por filas y por columnas (restar la media y dividir entre la desviación típica).